name: Code-Analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  analyze:
    container:
      image: faultaddr/ubuntu22.04-pcl:v3
      options: --user 1001
    name: Analyze
    runs-on: ubuntu-22.04
    permissions:
      actions: write
      contents: write
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        # Learn more about CodeQL language support at https://aka.ms/codeql-docs/language-support

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Configure CMake
      run:  cd 3DViewer && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} && make -j4 && cd ..
    - name: clang-format
      uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: '.'
        exclude: './src/log'
        extensions: 'h,cpp,c'
        clangFormatVersion: 12
        inplace: True
        style: chromium
    - name: format-result-push
      uses: EndBug/add-and-commit@v9
      with:
          author_name: robot
          author_email: robot@faultaddr.com
          message: 'format: clang format'
          add: '*'
          cwd: './3DViewer'
      env:
        GITHUB_TOKEN: ${{ secrets.ROBOT_SECRET }}
